version: '3'

services:
  postgres:
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
